# Generated by Django 4.2.2 on 2023-07-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='statustask',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.status'),
        ),
    ]
