# Generated by Django 4.2.2 on 2023-07-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_status_options_remove_task_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
